p8105_hw2_jh4617
================
Junjie Hu
2023-10-01

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.3     ✔ readr     2.1.4
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.0
    ## ✔ ggplot2   3.4.3     ✔ tibble    3.2.1
    ## ✔ lubridate 1.9.2     ✔ tidyr     1.3.0
    ## ✔ purrr     1.0.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library(readxl)
```

# Problem 1

Clean *pols* dataframe

``` r
pols = 
  read_csv("fivethirtyeight_datasets/pols-month.csv") |>
  janitor::clean_names() |>
  separate(mon, into = c("year", "month", "day") )|>
  mutate(president = recode(prez_gop, "0" = "dem", "1" = "gop", "2" = "gop")) |>
  mutate(month = recode(month,
                        "01" = "jan",
                        "02" = "feb",
                        "03" = "mar",
                        "04" = "apr",
                        "05" = "may",
                        "06" = "jun",
                        "07" = "jul",
                        "08" = "aug",
                        "09" = "sep",
                        "10" = "oct",
                        "11" = "nov",
                        "12" = "dec")) |>
  select(-prez_dem, -prez_gop, -day) |>
  arrange (year, month)
```

    ## Rows: 822 Columns: 9
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl  (8): prez_gop, gov_gop, sen_gop, rep_gop, prez_dem, gov_dem, sen_dem, r...
    ## date (1): mon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
head(pols)
```

    ## # A tibble: 6 × 9
    ##   year  month gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem president
    ##   <chr> <chr>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <chr>    
    ## 1 1947  apr        23      51     253      23      45     198 dem      
    ## 2 1947  aug        23      51     253      23      45     198 dem      
    ## 3 1947  dec        24      51     253      23      45     198 dem      
    ## 4 1947  feb        23      51     253      23      45     198 dem      
    ## 5 1947  jan        23      51     253      23      45     198 dem      
    ## 6 1947  jul        23      51     253      23      45     198 dem

Clean *snp* dataframe

``` r
snp = 
  read_csv("fivethirtyeight_datasets/snp.csv") |>
  janitor::clean_names() |>
  mutate(date = as.Date(date, format = "%m/%d/%y")) |>
  separate(date, into = c("year", "month", "day")) |>
  mutate(year = as.numeric(year), month = as.numeric(month)) |>
  mutate(year = ifelse(year > as.integer(format(Sys.Date(),"%Y")),
                       year - 100, year)) |>
  mutate(month = recode(month,
                        "1" = "jan",
                        "2" = "feb",
                        "3" = "mar",
                        "4" = "apr",
                        "5" = "may",
                        "6" = "jun",
                        "7" = "jul",
                        "8" = "aug",
                        "9" = "sep",
                        "10" = "oct",
                        "11" = "nov",
                        "12" = "dec"))|>
  select(-day) |>
  arrange(year, month) |>
  mutate(year = as.character(year))
```

    ## Rows: 787 Columns: 2
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): date
    ## dbl (1): close
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
head(snp)
```

    ## # A tibble: 6 × 3
    ##   year  month close
    ##   <chr> <chr> <dbl>
    ## 1 1950  apr    18.0
    ## 2 1950  aug    18.4
    ## 3 1950  dec    20.4
    ## 4 1950  feb    17.2
    ## 5 1950  jan    17.0
    ## 6 1950  jul    17.8

``` r
tail(snp)
```

    ## # A tibble: 6 × 3
    ##   year  month close
    ##   <chr> <chr> <dbl>
    ## 1 2015  feb   2104.
    ## 2 2015  jan   1995.
    ## 3 2015  jul   2080.
    ## 4 2015  jun   2063.
    ## 5 2015  mar   2068.
    ## 6 2015  may   2107.

Clean *unemployment* dataframe

``` r
unemployment = 
  read_csv("fivethirtyeight_datasets/unemployment.csv") |>
  janitor::clean_names() |>
  pivot_longer(
    jan:dec, 
    names_to = "month",
    values_to = "unemployment") |> 
  select(year, month, unemployment) |>
  mutate(year = as.character(year))
```

    ## Rows: 68 Columns: 13
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (13): Year, Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
head(unemployment)
```

    ## # A tibble: 6 × 3
    ##   year  month unemployment
    ##   <chr> <chr>        <dbl>
    ## 1 1948  jan            3.4
    ## 2 1948  feb            3.8
    ## 3 1948  mar            4  
    ## 4 1948  apr            3.9
    ## 5 1948  may            3.5
    ## 6 1948  jun            3.6

``` r
tail(unemployment)
```

    ## # A tibble: 6 × 3
    ##   year  month unemployment
    ##   <chr> <chr>        <dbl>
    ## 1 2015  jul             NA
    ## 2 2015  aug             NA
    ## 3 2015  sep             NA
    ## 4 2015  oct             NA
    ## 5 2015  nov             NA
    ## 6 2015  dec             NA

Merge *pols*, *snp*, and *unemployment* dataframes together

``` r
problem1_df = left_join(pols, snp) |> 
  left_join(unemployment, copy = TRUE)
```

    ## Joining with `by = join_by(year, month)`
    ## Joining with `by = join_by(year, month)`

``` r
problem1_df
```

    ## # A tibble: 822 × 11
    ##    year  month gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem president close
    ##    <chr> <chr>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <chr>     <dbl>
    ##  1 1947  apr        23      51     253      23      45     198 dem          NA
    ##  2 1947  aug        23      51     253      23      45     198 dem          NA
    ##  3 1947  dec        24      51     253      23      45     198 dem          NA
    ##  4 1947  feb        23      51     253      23      45     198 dem          NA
    ##  5 1947  jan        23      51     253      23      45     198 dem          NA
    ##  6 1947  jul        23      51     253      23      45     198 dem          NA
    ##  7 1947  jun        23      51     253      23      45     198 dem          NA
    ##  8 1947  mar        23      51     253      23      45     198 dem          NA
    ##  9 1947  may        23      51     253      23      45     198 dem          NA
    ## 10 1947  nov        24      51     253      23      45     198 dem          NA
    ## # ℹ 812 more rows
    ## # ℹ 1 more variable: unemployment <dbl>

# Problem 2

Clean *Mr.trash* dataframe

``` r
mr.trash = 
  read_excel("202309 Trash Wheel Collection Data.xlsx", sheet = 1) |>
  janitor::clean_names() |>
  mutate(homes_powered = weight_tons*500/30) |>
  drop_na(dumpster)
```

    ## New names:
    ## • `` -> `...15`
    ## • `` -> `...16`

``` r
mr.trash
```

    ## # A tibble: 584 × 16
    ##    dumpster month year  date                weight_tons volume_cubic_yards
    ##       <dbl> <chr> <chr> <dttm>                    <dbl>              <dbl>
    ##  1        1 May   2014  2014-05-16 00:00:00        4.31                 18
    ##  2        2 May   2014  2014-05-16 00:00:00        2.74                 13
    ##  3        3 May   2014  2014-05-16 00:00:00        3.45                 15
    ##  4        4 May   2014  2014-05-17 00:00:00        3.1                  15
    ##  5        5 May   2014  2014-05-17 00:00:00        4.06                 18
    ##  6        6 May   2014  2014-05-20 00:00:00        2.71                 13
    ##  7        7 May   2014  2014-05-21 00:00:00        1.91                  8
    ##  8        8 May   2014  2014-05-28 00:00:00        3.7                  16
    ##  9        9 June  2014  2014-06-05 00:00:00        2.52                 14
    ## 10       10 June  2014  2014-06-11 00:00:00        3.76                 18
    ## # ℹ 574 more rows
    ## # ℹ 10 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, sports_balls <dbl>, homes_powered <dbl>, x15 <lgl>,
    ## #   x16 <lgl>

Clean *professor_trash* and *gwynnada_trash* dataframe

``` r
professor_trash = 
  read_excel("202309 Trash Wheel Collection Data.xlsx", sheet = 2) |>
  janitor::clean_names() |>
  mutate(homes_powered = weight_tons*500/30) |>
  mutate(year = as.character(year)) |>
  drop_na(dumpster)

professor_trash
```

    ## # A tibble: 106 × 13
    ##    dumpster month    year  date                weight_tons volume_cubic_yards
    ##       <dbl> <chr>    <chr> <dttm>                    <dbl>              <dbl>
    ##  1        1 January  2017  2017-01-02 00:00:00        1.79                 15
    ##  2        2 January  2017  2017-01-30 00:00:00        1.58                 15
    ##  3        3 February 2017  2017-02-26 00:00:00        2.32                 18
    ##  4        4 February 2017  2017-02-26 00:00:00        3.72                 15
    ##  5        5 February 2017  2017-02-28 00:00:00        1.45                 15
    ##  6        6 March    2017  2017-03-30 00:00:00        1.71                 15
    ##  7        7 April    2017  2017-04-01 00:00:00        1.82                 15
    ##  8        8 April    2017  2017-04-20 00:00:00        2.37                 15
    ##  9        9 May      2017  2017-05-10 00:00:00        2.64                 15
    ## 10       10 May      2017  2017-05-26 00:00:00        2.78                 15
    ## # ℹ 96 more rows
    ## # ℹ 7 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, homes_powered <dbl>

``` r
gwynnda_trash = 
  read_excel("202309 Trash Wheel Collection Data.xlsx", sheet = 4) |>
  janitor::clean_names() |>
  mutate(homes_powered = weight_tons*500/30) |>
  mutate(year = as.character(year)) |>
  drop_na(dumpster)

gwynnda_trash
```

    ## # A tibble: 155 × 12
    ##    dumpster month  year  date                weight_tons volume_cubic_yards
    ##       <dbl> <chr>  <chr> <dttm>                    <dbl>              <dbl>
    ##  1        1 July   2021  2021-07-03 00:00:00        0.93                 15
    ##  2        2 July   2021  2021-07-07 00:00:00        2.26                 15
    ##  3        3 July   2021  2021-07-07 00:00:00        1.62                 15
    ##  4        4 July   2021  2021-07-16 00:00:00        1.76                 15
    ##  5        5 July   2021  2021-07-30 00:00:00        1.53                 15
    ##  6        6 August 2021  2021-08-11 00:00:00        2.06                 15
    ##  7        7 August 2021  2021-08-14 00:00:00        1.9                  15
    ##  8        8 August 2021  2021-08-16 00:00:00        2.16                 15
    ##  9        9 August 2021  2021-08-16 00:00:00        2.6                  15
    ## 10       10 August 2021  2021-08-17 00:00:00        3.21                 15
    ## # ℹ 145 more rows
    ## # ℹ 6 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, plastic_bags <dbl>, wrappers <dbl>,
    ## #   homes_powered <dbl>

Merage *mr.trash*, *professor_trash*, and *gwynnda_trash* dataframes

``` r
trash_df =
  full_join(mr.trash, professor_trash) |>
  full_join(gwynnda_trash, copy = TRUE) |>
  select(-x15, -x16)
```

    ## Joining with `by = join_by(dumpster, month, year, date, weight_tons,
    ## volume_cubic_yards, plastic_bottles, polystyrene, cigarette_butts,
    ## glass_bottles, plastic_bags, wrappers, homes_powered)`
    ## Joining with `by = join_by(dumpster, month, year, date, weight_tons,
    ## volume_cubic_yards, plastic_bottles, polystyrene, cigarette_butts,
    ## plastic_bags, wrappers, homes_powered)`

``` r
trash_df
```

    ## # A tibble: 845 × 14
    ##    dumpster month year  date                weight_tons volume_cubic_yards
    ##       <dbl> <chr> <chr> <dttm>                    <dbl>              <dbl>
    ##  1        1 May   2014  2014-05-16 00:00:00        4.31                 18
    ##  2        2 May   2014  2014-05-16 00:00:00        2.74                 13
    ##  3        3 May   2014  2014-05-16 00:00:00        3.45                 15
    ##  4        4 May   2014  2014-05-17 00:00:00        3.1                  15
    ##  5        5 May   2014  2014-05-17 00:00:00        4.06                 18
    ##  6        6 May   2014  2014-05-20 00:00:00        2.71                 13
    ##  7        7 May   2014  2014-05-21 00:00:00        1.91                  8
    ##  8        8 May   2014  2014-05-28 00:00:00        3.7                  16
    ##  9        9 June  2014  2014-06-05 00:00:00        2.52                 14
    ## 10       10 June  2014  2014-06-11 00:00:00        3.76                 18
    ## # ℹ 835 more rows
    ## # ℹ 8 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, sports_balls <dbl>, homes_powered <dbl>

There are 584 observations in the Mr.trash file.

There are 106 observations in the professor_trash file.

There are 155 observations in the gwynnda_trash file.

There are 845 observations in merged data, including 14 variables and
key variables dumpster, month, year, date, weight_tons,
volume_cubic_yards, plastic_bottles, polystyrene, cigarette_butts,
glass_bottles, plastic_bags, wrappers, sports_balls, homes_powered.

The total weight of trash collected by Professor Trash Wheel is 216.26.

The total number of cigarette butts collected by Gwynnda in July of 2021
is 1.63^{4}.

# problem 3

Clean *MCI_baseline* data

``` r
MCI_baseline = 
  read.csv("data_mci/MCI_baseline.csv")|>
  slice(-1) |>
  magrittr::set_colnames(c("ID", "current_age", "sex", "education", "apoe4", "age_at_onset"))|>
  janitor::clean_names() |>
  mutate(age_at_onset = ifelse(age_at_onset == ".", NA, age_at_onset),
         current_age = as.numeric(current_age),
         age_at_onset = as.numeric(age_at_onset),
         sex = recode(sex, "0" = "male", "1" = "female"), 
         apoe4 = recode(apoe4, "0" = "non-carrier", "1" = "carrier")) |>
  filter(current_age < age_at_onset | is.na(age_at_onset))
```

There are 479 participants were recruited.

Of the recruited participants, 93 participants have developed MCI.

The average baseline age is 65.0286013.

There are 30.1115242 % of women in the study are APOE4 carriers.

Clean *mci_amyloid* datafile

``` r
mci_amyloid = 
  read.csv("data_mci/mci_amyloid.csv") |>
  slice(-1) |>
  magrittr::set_colnames(c("ID","baseline","time2","time4","time6","time8")) |>
  janitor::clean_names() |>
  pivot_longer(
    baseline:time8,
    names_to = "time",
    values_to = "amyloid_ratio" 
  )
  
mci_amyloid
```

    ## # A tibble: 2,435 × 3
    ##    id    time     amyloid_ratio
    ##    <chr> <chr>    <chr>        
    ##  1 1     baseline 0.1105487    
    ##  2 1     time2    <NA>         
    ##  3 1     time4    0.109325197  
    ##  4 1     time6    0.104756131  
    ##  5 1     time8    0.107257697  
    ##  6 2     baseline 0.107481183  
    ##  7 2     time2    0.109157373  
    ##  8 2     time4    0.109457839  
    ##  9 2     time6    0.105729713  
    ## 10 2     time8    0.10661845   
    ## # ℹ 2,425 more rows
